version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx:1.13
    restart: always
    ports:
      - 80:80
    volumes:
      - ./src/main/resources/static:/etc/nginx/html/signin
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - app-network

  app:
    container_name: spring-boot-app
    build:
      dockerfile: Dockerfile
    expose:
      - "8080"
    depends_on:
      - nginx
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
